# Generated by Django 3.2.8 on 2021-10-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='user id'),
        ),
    ]
