# Generated by Django 3.2.8 on 2021-11-20 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriend',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='UserFriend',
        ),
    ]
