# Generated by Django 3.2.8 on 2021-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0002_auto_20211025_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.IntegerField(null=True, unique=True, verbose_name='profile'),
        ),
    ]
