# Generated by Django 3.2.8 on 2021-11-20 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0002_auto_20211120_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='chat_users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
