# Generated by Django 3.2.8 on 2021-10-29 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='profile id')),
                ('language', models.CharField(default='en', max_length=2, verbose_name='language')),
                ('theme', models.CharField(default='Light', max_length=20, verbose_name='theme')),
                ('contact_id', models.IntegerField(unique=True, verbose_name='contact id')),
                ('profile_img', models.ImageField(null=True, upload_to='', verbose_name='profile img')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='message id')),
                ('text', models.TextField(max_length=300, verbose_name='text')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rephrase.user', verbose_name='user id')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rephrase.profile', verbose_name='profile'),
        ),
    ]
