# Generated by Django 3.2.8 on 2021-10-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0004_auto_20211028_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
