# Generated by Django 3.2.8 on 2021-10-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0005_rename_user_id_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False, verbose_name='server id')),
                ('name', models.CharField(max_length=50, verbose_name='server name')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='message id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rephrase.user', verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='profile id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='user id'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='chat id')),
                ('name', models.CharField(max_length=50, verbose_name='chat name')),
                ('server_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rephrase.server', verbose_name='server id')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='rephrase.chat', verbose_name='chat id'),
        ),
    ]
