# Generated by Django 3.2.8 on 2021-10-31 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0006_auto_20211030_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=2, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='Light', max_length=20, null=True, verbose_name='theme'),
        ),
    ]
