# Generated by Django 3.2.8 on 2021-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0007_auto_20211031_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='contact id'),
        ),
    ]
