# Generated by Django 3.2.8 on 2021-11-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0008_alter_profile_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='contact id'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=5, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='profile img'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='Light', max_length=20, null=True, verbose_name='theme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rephrase.user', verbose_name='user id'),
        ),
    ]
