# Generated by Django 3.2.8 on 2021-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0009_auto_20211101_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images', verbose_name='profile img'),
        ),
    ]
