# Generated by Django 3.2.8 on 2021-11-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0009_auto_20211102_2124'),
        ('rephrase', '0010_alter_user_profile_img'),
    ]

    operations = [
    ]
