# Generated by Django 3.2.8 on 2021-11-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0011_merge_20211105_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_id',
        ),
    ]
