# Generated by Django 3.2.8 on 2021-11-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
