# Generated by Django 3.2.8 on 2021-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephrase', '0014_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='default.jpg', null=True, upload_to='images', verbose_name='profile img'),
        ),
    ]
